[font]
normal = {family = "JetBrainsMono Nerd Font Mono", style = "Regular"}
bold = {family = "JetBrainsMono Nerd Font Mono", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font Mono", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic"}
size = 20

[window]
startup_mode = "Maximized"
decorations = "Buttonless"

opacity = 0.8

padding.x = 12

[keyboard]
# tmux windows from 0-4
bindings = [
  {key = "1", mods = "Command", chars = "\u0013\u0030"},
  {key = "2", mods = "Command", chars = "\u0013\u0031"},
  {key = "3", mods = "Command", chars = "\u0013\u0032"},
  {key = "4", mods = "Command", chars = "\u0013\u0033"},
  {key = "5", mods = "Command", chars = "\u0013\u0034"},
  # same as above but with arrows
  {mods = "Command|Option", key = "Left",  chars = "\u0013\u0070"},
  {mods = "Command|Option", key = "Right", chars = "\u0013\u006E"},
  {key = "Equals", mods = "Command", action = "IncreaseFontSize"},
  {key = "Minus", mods = "Command", action = "DecreaseFontSize"},
  {key = "0", mods = "Command", action = "ResetFontSize"}
]

